description: Base MISO training job 

target: 
  service: amlk8s
  name: itpeusp40cl
  vc: resrchvc

environment:
  image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
  registry: docker.io # any public registry can be specified here
code:
   local_dir: $CONFIG_DIR/../../..

data:
   local_dir: $CONFIG_DIR/../../../resources/data/
   remote_dir: resources/data


storage:
   output:
       storage_account_name: ysumiso
       container_name: ysumiso
       mount_dir: /mnt/output

jobs: 
    - name: train_transformer_full
      sku: G1
      command: 
        - pwd
        - ls
        - export CHECKPOINT_DIR=/mnt/output/transformer/FindManager_12_seed/5000_100
        - ls /mnt
        - ls /mnt/default
        - ls /mnt/default//data
        - ls /mnt/default//data/smcalflow_samples_curated
        - ls /mnt/default//data/smcalflow_samples_curated/FindManager
        - ls /mnt/default//data/smcalflow_samples_curated/FindManager/5000_100
        - export TRAINING_CONFIG=miso/training_config/calflow_transformer_many_save/FindManager/12_seed/5000_100.jsonnet 
        - echo "DONE"

