description: Base MISO training job 

target: 
  service: amlk8s
  name: itpeusp40cl
  vc: resrchvc

environment:
  image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
  registry: docker.io # any public registry can be specified here
  setup:
    - pip install allennlp==0.9.0 --user
    - pip install tensorboard --user
    - pip install torch==1.4.0 --user 
    - pip install torch==1.4.0 --user
    - pip install overrides==3.1.0 --user
    - pip install pycorenlp --user
    - pip install penman==0.6.2 --user
    - pip install editdistance --user
    - pip install word2numer --user
    - pip install bs4 --user
    - pip install lxml --user 
    - pip install networkx --user
    - pip install sentencepiece==0.1.91 --user
    - pip install transformers==3.0.2 --user
    - pip install icecream --user
    - pip install git+git://github.com/decompositional-semantics-initiative/decomp.git --user 
    - pip install git+https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis --user
code:
   local_dir: $CONFIG_DIR/../../

data:
   local_dir: $CONFIG_DIR/../../../resources/data/
   remote_dir: resources/data


storage:
   output:
       storage_account_name: elias
       container_name: miso
       mount_dir: /mnt/output

jobs: 
    - name: train_transformer_full
      sku: G1
      command: 
        - cd $CONFIG_DIR/../../
        - export CHECKPOINT_DIR=models/train_test_out
        - export CHECKPOINT_DIR=/mnt/output/transformer_full
        - export TRAINING_CONFIG=miso/training_config/calflow_transformer/agent_aml.jsonnet
        - python -m spacy download en_core_web_sm
        - ./experiments/calflow.sh -a train

