description: Base MISO training job 

target: 
  service: amlk8s
  name: itpeusp40cl
  vc: resrchvc

environment:
  image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
  registry: docker.io # any public registry can be specified here

code:
   local_dir: $CONFIG_DIR/../

data:
   local_dir: $CONFIG_DIR/../../resources/data/
   remote_dir: resources/data

storage:
   output:
       storage_account_name: elias
       container_name: miso
       mount_dir: /mnt/output

jobs: 
    - name: miso_train
      sku: G1
      command: 
        - cd $CONFIG_DIR/..
        - export CHECKPOINT_DIR=models/train_test_out
        - export TRAINING_CONFIG=miso/training_config/calflow_lstm/overfit_calflow_aml.jsonnet
        - ./experiments/calflow_aml_debug.sh -a train

