description: Base MISO training job 

target: 
  service: amlk8s
  name: itpeusp40cl
  vc: resrchvc

environment:
  image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
  registry: docker.io # any public registry can be specified here
  setup:
     - pip install allennlp==0.9.0 --user
     - pip install tensorboard --user
     - pip install torch==1.4.0 --user 
     - pip install torch==1.4.0 --user
     - pip install overrides==3.1.0 --user
     - pip install pycorenlp --user
     - pip install penman==0.6.2 --user
     - pip install editdistance --user
     - pip install word2numer --user
     - pip install bs4 --user
     - pip install lxml --user 
     - pip install networkx --user
     - pip install sentencepiece==0.1.91 --user
     - pip install transformers==3.0.2 --user
     - pip install icecream --user
     - pip install datasets --user
     - pip install git+git://github.com/decompositional-semantics-initiative/decomp.git --user 
     - pip install git+https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis --user
code:
   local_dir: $CONFIG_DIR/../../..

data:
   local_dir: $CONFIG_DIR/../../../../resources/data/
   remote_dir: resources/data


storage:
   output:
       storage_account_name: elias
       container_name: miso
       mount_dir: /mnt/output

jobs: 
    - name: train
      sku: G1
      command: 
        - export CHECKPOINT_DIR=/mnt/output/transformer_min_pair/DoNotConfirm_31_seed/5000_500
        - export TRAINING_CONFIG=miso/training_config/calflow_transformer_min_pair_random_baseline/DoNotConfirm/31_seed/5000_500.jsonnet 
        - echo "DONE"
        - ./experiments/calflow.sh -a train
        - export FXN=DoNotConfirm
        - export CHECKPOINT_DIR=/mnt/output/transformer_min_pair/DoNotConfirm_31_seed/5000_500
        - export TEST_DATA=/mnt/default/resources/data/smcalflow_samples_big/DoNotConfirm/5000_500/dev_valid
        - ./experiments/calflow.sh -a eval_fxn
        - export CHECKPOINT_DIR=/mnt/output/transformer_min_pair/DoNotConfirm_31_seed/5000_500
        - export TEST_DATA=/mnt/default/resources/data/smcalflow_samples_big/DoNotConfirm/5000_500/test_valid
        - ./experiments/calflow.sh -a eval_fxn

    - name: decode
      sku: G1
      command:
         - export CHECKPOINT_DIR=/mnt/output/transformer_min_pair/DoNotConfirm_31_seed/5000_500
         - export TEST_DATA=/mnt/default/resources/data/smcalflow_samples_big/DoNotConfirm/5000_500/dev_valid
         - export FXN=DoNotConfirm
         - ./experiments/calflow.sh -a eval_fxn

    - name: decode_test
      sku: G1
      command:
         - export CHECKPOINT_DIR=/mnt/output/transformer_min_pair/DoNotConfirm_31_seed/5000_500
         - export TEST_DATA=/mnt/default/resources/data/smcalflow_samples_big/DoNotConfirm/5000_500/test_valid
         - export FXN=DoNotConfirm
         - ./experiments/calflow.sh -a eval_fxn



